### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'find'

### ISSUE THREAD

**Issue by LeilaNantes** [kundajelab/atac_dnase_pipelines#101]
Hi !

I have got this message at the end of the run : 

" [...]
AttributeError: 'Series' object has no attribute 'find'
[...]
Fatal error: atac.bds, line 1616, pos 2. Task/s failed. "

It seems to be a problem with Pandas but I don't know how to fix it

Last lines of the run : 

Traceback (most recent call last):
  File "/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/ataqc/run_ataqc.py", line 1654, in <module>
    main()
  File "/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/ataqc/run_ataqc.py", line 1603, in main
    ('gc_bias', plot_gc(gc_out)),
  File "/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/ataqc/run_ataqc.py", line 259, in plot_gc
    label='Normalized coverage', color='r')
  File "/sandbox/users/lbenesteau/anaconda3/envs/bds_atac/lib/python2.7/site-packages/matplotlib/__init__.py", line 1812, in inner
    return func(ax, *args, **kwargs)
  File "/sandbox/users/lbenesteau/anaconda3/envs/bds_atac/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 1424, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/sandbox/users/lbenesteau/anaconda3/envs/bds_atac/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 386, in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
  File "/sandbox/users/lbenesteau/anaconda3/envs/bds_atac/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 336, in _plot_args
    linestyle, marker, color = _process_plot_format(tup[-1])
  File "/sandbox/users/lbenesteau/anaconda3/envs/bds_atac/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 86, in _process_plot_format
    if fmt.find('--') >= 0:
  File "/sandbox/users/lbenesteau/anaconda3/envs/bds_atac/lib/python2.7/site-packages/pandas/core/generic.py", line 3614, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'find'
bedtools sort -i /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/ataqc/reg2map_honeybadger2_dnase_all_p10_ucsc.bed.gz  | bedtools merge -i stdin | bedtools intersect -u -nonamecheck -a /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz -b stdin | wc -l
zcat -f /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz | wc -l
bedtools sort -i /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/wgEncodeDacMapabilityConsensusExcludable.bed.gz  | bedtools merge -i stdin | bedtools intersect -u -nonamecheck -a /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz -b stdin | wc -l
zcat -f /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz | wc -l
bedtools sort -i /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/ataqc/reg2map_honeybadger2_dnase_prom_p2.bed.gz  | bedtools merge -i stdin | bedtools intersect -u -nonamecheck -a /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz -b stdin | wc -l
zcat -f /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz | wc -l
bedtools sort -i /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/ataqc/reg2map_honeybadger2_dnase_enh_p2.bed.gz  | bedtools merge -i stdin | bedtools intersect -u -nonamecheck -a /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz -b stdin | wc -l
zcat -f /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz | wc -l
bedtools sort -i /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/peak/macs2/overlap/optimal_set/NTS-127_all_ppr.naive_overlap.filt.narrowPeak.gz  | bedtools merge -i stdin | bedtools intersect -u -nonamecheck -a /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz -b stdin | wc -l
zcat -f /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz | wc -l
Task failed:
	Program & line     : 'modules/ataqc.bds', line 109
	Task Name          : 'ataqc rep2'
	Task ID            : 'atac.bds.20180409_093402_469_parallel_221/task.ataqc.ataqc_rep2.line_109.id_100'
	Task PID           : '49381'
	Task hint          : 'if [ "/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/tmp" != "" ] && [ -d "/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/tmp" ]; then; fi; cd /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/qc/rep2; /sandbox/users/lbenesteau/NTS-12'
	Task resources     : 'cpus: -1	mem: -1,0 B	wall-timeout: 8640000'
	State              : 'ERROR'
	Dependency state   : 'ERROR'
	Retries available  : '1'
	Input files        : '[/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/fastqConcat/i_C2_2a_p55.5_17_R1.fastq.gz, /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/fastqConcat/i_C2_2a_p55.5_17_R2.fastq.gz, /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.bam, /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/qc/rep2/i_C2_2a_p55.5_17_R1.PE2SE.align.log, /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/qc/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.pbc.qc, /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/qc/rep2/i_C2_2a_p55.5_17_R1.PE2SE.dup.qc, /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.bam, /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz, /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/signal/macs2/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.pf.pval.signal.bigwig, /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/peak/macs2/overlap/optimal_set/NTS-127_all_ppr.naive_overlap.filt.narrowPeak.gz]'
	Output files       : '[/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/qc/rep2/i_C2_2a_p55.5_17_R1.PE2SE_qc.html, /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/qc/rep2/i_C2_2a_p55.5_17_R1.PE2SE_qc.txt]'
	Script file        : '/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/atac.bds.20180409_093402_469_parallel_221/task.ataqc.ataqc_rep2.line_109.id_100.sh'
	Exit status        : '1'
	Program            : 
		
		# SYS command. line 111
		
		 if [[ -f $(which conda) && $(conda env list | grep bds_atac | wc -l) != "0" ]]; then source activate bds_atac; sleep 5; fi;  export PATH=/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/.:/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/modules:/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/utils:${PATH}:/bin:/usr/bin:/usr/local/bin:${HOME}/.bds; set -o pipefail; STARTTIME=$(date +%s)
		
		# SYS command. line 114
		
		 export _JAVA_OPTIONS="-Xms256M -Xmx20G -XX:ParallelGCThreads=1"
		
		# SYS command. line 116
		
		 if [ "/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/tmp" != "" ] && [ -d "/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/tmp" ]; then \
					export _JAVA_OPTIONS="${_JAVA_OPTIONS} -Djava.io.tmpdir=/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/tmp"; \
				fi
		
		# SYS command. line 119
		
		 cd /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/qc/rep2
		
		# SYS command. line 122
		
		 if [ -f "$(which picard)" ]; then export PICARDROOT="$(dirname $(which picard))/../share/picard"*; fi
		
		# SYS command. line 124
		
		 /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/ataqc/run_ataqc.py \
				    --workdir /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/qc/rep2 \
				    --outdir /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/qc/rep2 \
				    --outprefix i_C2_2a_p55.5_17_R1.PE2SE \
				    --genome hg19 \
				    --chromsizes /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/hg19.chrom.sizes \
				    --ref /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/male.hg19.fa \
				    --tss /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/ataqc/hg19_gencode_tss_unique.bed.gz \
				    --dnase /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/ataqc/reg2map_honeybadger2_dnase_all_p10_ucsc.bed.gz \
				    --blacklist /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/wgEncodeDacMapabilityConsensusExcludable.bed.gz \
				    --prom /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/ataqc/reg2map_honeybadger2_dnase_prom_p2.bed.gz \
				    --enh /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/ataqc/reg2map_honeybadger2_dnase_enh_p2.bed.gz \
				    --pbc /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/qc/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.pbc.qc\
				     --fastq1 /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/fastqConcat/i_C2_2a_p55.5_17_R1.fastq.gz --fastq2 /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/fastqConcat/i_C2_2a_p55.5_17_R2.fastq.gz \
				    --alignedbam /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.bam \
				    --alignmentlog /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/qc/rep2/i_C2_2a_p55.5_17_R1.PE2SE.align.log \
				    --coordsortbam /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.bam \
				    --duplog /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/qc/rep2/i_C2_2a_p55.5_17_R1.PE2SE.dup.qc \
				    --finalbam /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.bam \
				    --finalbed /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz \
				    --bigwig /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/signal/macs2/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.pf.pval.signal.bigwig \
				    --peaks /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/peak/macs2/overlap/optimal_set/NTS-127_all_ppr.naive_overlap.filt.narrowPeak.gz  --naive_overlap_peaks /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/peak/macs2/overlap/optimal_set/NTS-127_all_ppr.naive_overlap.filt.narrowPeak.gz   \
				     --reg2map /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/ataqc/dnase_avgs_reg2map_p10_merged_named.pvals.gz  --reg2map_bed /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/ataqc/reg2map_honeybadger2_dnase_all_p10_ucsc.bed.gz  --meta /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/ataqc/eid_to_mnemonic.txt
		
		# SYS command. line 147
		
		 rm -f test.log test.png
		
		# SYS command. line 149
		
		 TASKTIME=$[$(date +%s)-${STARTTIME}]; echo "Task has finished (${TASKTIME} seconds)."; sleep 0
	StdErr (100000000 lines)  :
		Picked up _JAVA_OPTIONS: -Xms256M -Xmx20G -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/tmp
		ERROR	2018-04-09 09:42:29	ProcessExecutor	Warning messages:
		ERROR	2018-04-09 09:42:29	ProcessExecutor	1: In Ops.factor(metrics$NORMALIZED_COVERAGE, metrics$ERROR_BAR_WIDTH) :
		ERROR	2018-04-09 09:42:29	ProcessExecutor	  ‘-’ not meaningful for factors
		ERROR	2018-04-09 09:42:29	ProcessExecutor	2: In Ops.factor(metrics$NORMALIZED_COVERAGE, metrics$ERROR_BAR_WIDTH) :
		ERROR	2018-04-09 09:42:29	ProcessExecutor	  ‘+’ not meaningful for factors
		Picked up _JAVA_OPTIONS: -Xms256M -Xmx20G -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/tmp
		[bam_sort_core] merging from 58 files...
		[bam_sort_core] merging from 55 files...
		Picked up _JAVA_OPTIONS: -Xms256M -Xmx20G -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/tmp
		Picked up _JAVA_OPTIONS: -Xms256M -Xmx20G -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/tmp
		processing chromosomes
		Traceback (most recent call last):
		  File "/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/ataqc/run_ataqc.py", line 1654, in <module>
		    main()
		  File "/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/ataqc/run_ataqc.py", line 1603, in main
		    ('gc_bias', plot_gc(gc_out)),
		  File "/sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/atac_dnase_pipelines/ataqc/run_ataqc.py", line 259, in plot_gc
		    label='Normalized coverage', color='r')
		  File "/sandbox/users/lbenesteau/anaconda3/envs/bds_atac/lib/python2.7/site-packages/matplotlib/__init__.py", line 1812, in inner
		    return func(ax, *args, **kwargs)
		  File "/sandbox/users/lbenesteau/anaconda3/envs/bds_atac/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 1424, in plot
		    for line in self._get_lines(*args, **kwargs):
		  File "/sandbox/users/lbenesteau/anaconda3/envs/bds_atac/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 386, in _grab_next_args
		    for seg in self._plot_args(remaining, kwargs):
		  File "/sandbox/users/lbenesteau/anaconda3/envs/bds_atac/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 336, in _plot_args
		    linestyle, marker, color = _process_plot_format(tup[-1])
		  File "/sandbox/users/lbenesteau/anaconda3/envs/bds_atac/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 86, in _process_plot_format
		    if fmt.find('--') >= 0:
		  File "/sandbox/users/lbenesteau/anaconda3/envs/bds_atac/lib/python2.7/site-packages/pandas/core/generic.py", line 3614, in __getattr__
		    return object.__getattribute__(self, name)
		AttributeError: 'Series' object has no attribute 'find'
	StdOut (100000000 lines)  :
		bedtools sort -i /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/ataqc/reg2map_honeybadger2_dnase_all_p10_ucsc.bed.gz  | bedtools merge -i stdin | bedtools intersect -u -nonamecheck -a /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz -b stdin | wc -l
		zcat -f /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz | wc -l
		bedtools sort -i /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/wgEncodeDacMapabilityConsensusExcludable.bed.gz  | bedtools merge -i stdin | bedtools intersect -u -nonamecheck -a /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz -b stdin | wc -l
		zcat -f /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz | wc -l
		bedtools sort -i /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/ataqc/reg2map_honeybadger2_dnase_prom_p2.bed.gz  | bedtools merge -i stdin | bedtools intersect -u -nonamecheck -a /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz -b stdin | wc -l
		zcat -f /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz | wc -l
		bedtools sort -i /sandbox/users/lbenesteau/ATAC_DATA_DIR/hg19/ataqc/reg2map_honeybadger2_dnase_enh_p2.bed.gz  | bedtools merge -i stdin | bedtools intersect -u -nonamecheck -a /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz -b stdin | wc -l
		zcat -f /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz | wc -l
		bedtools sort -i /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/peak/macs2/overlap/optimal_set/NTS-127_all_ppr.naive_overlap.filt.narrowPeak.gz  | bedtools merge -i stdin | bedtools intersect -u -nonamecheck -a /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz -b stdin | wc -l
		zcat -f /sandbox/users/lbenesteau/NTS-127_NGS_Barc_ATAC-Seq/analyse/out/align/rep2/i_C2_2a_p55.5_17_R1.PE2SE.nodup.tn5.tagAlign.gz | wc -l

Fatal error: atac.bds, line 1616, pos 2. Task/s failed.

Thanks for the help

**Comment by vervacity** [comment]
It's either a pandas error or a picard error (caused by a different version) - if you have the *_gc.txt file in the qc folder, could you pass that along, your picard version, and also your pandas version? thanks!
