### ISSUE TITLE
Memory specification

### ISSUE THREAD

**Issue by albertoriva** [kundajelab/atac_dnase_pipelines#73]
Hello,

I'm running the pipeline on a slurm cluster with -nth 24, and I have three fastq files so the pipeline is running three bowtie jobs giving 8 cpus to each job. But since the default memory allocation is 7G, each bowtie job gets about 1.6G, which I'm afraid is too little. I tried increasing it with the -memory parameter, using "-memory 72G", but nothing changes. If I use -mem instead of -memory I get a Java error saying that that 72G is an invalid number, although the documentation says that -memory should be equivalent to -mem:

Exception in thread "main" java.lang.NumberFormatException: For input string: "72G"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at org.bds.lang.Type.parse(Type.java:334)
        at org.bds.BdsParseArgs.parseArgs(BdsParseArgs.java:207)
        at org.bds.BdsParseArgs.initializeArgs(BdsParseArgs.java:150)
        at org.bds.BdsParseArgs.initializeArgs(BdsParseArgs.java:106)
        at org.bds.BdsParseArgs.parse(BdsParseArgs.java:172)
        at org.bds.Bds.runCompile(Bds.java:872)
        at org.bds.Bds.run(Bds.java:815)
        at org.bds.Bds.main(Bds.java:182)

**Comment by leepc12** [comment]
Memory allocation parameters (`-mem_APPNAME` for a specific job and
`-memory` for all the others) are not total memory for the whole pipeline
run. So no matter how many bowtie2 jobs are submitted to slurm, the memory
limit for each is 7GB.

It is not recommended to use the default memory allocation (`-memory`)
since it changes memory limit for all tasks except those with their own
`-mem_[APPNAME]` parameters. Try `-mem_bwt2` instead.

Thanks,

Jin

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#m_2210836363000819449_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by albertoriva** [comment]
OK, thanks. It still seems that there's a bug in parsing the value of the -mem option, though...

**Comment by leepc12** [comment]
`-mem` bug is a known issue and it cannot be fixed.`mem` is already taken as an internal parameter variable in BDS language so BDS and java complains if `-mem` is not an integer (bytes).

Please use `-memory` instead of `-mem`.
