### ISSUE TITLE
Error sorting data frame in run_atacqc.py

### ISSUE THREAD

**Issue by AidanQuinn** [kundajelab/atac_dnase_pipelines#85]
I have an issue when running the standard ATACseq pipeline on a single sample (PE data) on a local machine. It seems like the error is with sorting a data frame (should use sort_values instead?), but I can't pin it down exactly. Do you know if this is a bug or something specific to my installation?

Standard error for below, thank you for your help.

> --------------------Stderr--------------------
> /home/local/aidan/yes/envs/bds_atac/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
>   warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
> Picked up _JAVA_OPTIONS: -Xms256M -Xmx20G -XX:ParallelGCThreads=1
> ERROR	2017-12-12 18:05:20	ProcessExecutor	Warning messages:
> ERROR	2017-12-12 18:05:20	ProcessExecutor	1: In arrows(metrics$GC, metrics$NORMALIZED_COVERAGE - metrics$ERROR_BAR_WIDTH,  :
> ERROR	2017-12-12 18:05:20	ProcessExecutor	  zero-length arrow is of indeterminate angle and so skipped
> ERROR	2017-12-12 18:05:20	ProcessExecutor	2: In arrows(metrics$GC, metrics$NORMALIZED_COVERAGE - metrics$ERROR_BAR_WIDTH,  :
> ERROR	2017-12-12 18:05:20	ProcessExecutor	  zero-length arrow is of indeterminate angle and so skipped
> Picked up _JAVA_OPTIONS: -Xms256M -Xmx20G -XX:ParallelGCThreads=1
> [bam_sort_core] merging from 46 files...
> [bam_sort_core] merging from 44 files...
> Picked up _JAVA_OPTIONS: -Xms256M -Xmx20G -XX:ParallelGCThreads=1
> Picked up _JAVA_OPTIONS: -Xms256M -Xmx20G -XX:ParallelGCThreads=1
> processing chromosomes
> Traceback (most recent call last):
>   File "/home/local/aidan/atac_dnase_pipelines/ataqc/run_ataqc.py", line 1654, in 
>     main()
>   File "/home/local/aidan/atac_dnase_pipelines/ataqc/run_ataqc.py", line 1516, in main
>     ROADMAP_META, OUTPUT_PREFIX)
>   File "/home/local/aidan/atac_dnase_pipelines/ataqc/run_ataqc.py", line 971, in compare_to_roadmap
>     sorted_results = merged.sort('corr', ascending=True)
>   File "/home/local/aidan/yes/envs/bds_atac/lib/python2.7/site-packages/pandas/core/generic.py", line 3614, in __getattr__
>     return object.__getattribute__(self, name)
> AttributeError: 'DataFrame' object has no attribute 'sort'

**Comment by AidanQuinn** [comment]
fixed, thank you!
