### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by ahorn720** [kundajelab/atac_dnase_pipelines#96]
I am able to run 
`~/.bds/bds ~/ATACseq/scripts/atac_dnase_pipelines/atac.bds` 
and I see the help menu however, when i run with arguments (seen below) i get the an error leading me to believe that my install did not work correctly.

Command:
```
bds atac.bd~/.bds/bds ~/ATACseq/scripts/atac_dnase_pipelines/atac.bds \
        -species /home/ahorning/ATACseq/scripts/atac_dnase_pipelines/genome_data/hg38 \
        -enable_idr \
        -auto_detect_adapter TRUE \
        -out_dir "${sample}_Peaks_pipeline_out" \
        -title "${sample}" \
        -gensz hm \
        -chrsz /home/ahorning/ATACseq/scripts/hg38.chrom.sizes \
        -seq_dir /srv/gsfs0/shared_data/RefGenomes/GATK_Resource_Bundle/hg38/ \
        -fastq1_1 "${files[0]}" \
        -fastq1_2 "${files[1]}"
```

Error (bowtie related maybe?):
```
== checking atac parameters ...
00:00:00.312    Error (/home/ahorning/ATACseq/scripts/atac_dnase_pipelines/modules/align_bowtie2.bds, line 44, pos 3): Bowtie2 index (-bwt2_idx) doesn't exists! (file: .1.bt2 or .1.bt2l)
```

Interestingly, i always had trouble running the `install_dependencies.sh` script. I'd always get the below error even after `cp bds.config ./utils/bds_scr $HOME/.bds`.

Error after running `install_dependencies.sh`:
```
[ahorning@smsx10srw-srcf-d15-37 atac_dnase_pipelines]$ bash install_dependencies.sh 
Traceback (most recent call last):
  File "/home/ahorning/miniconda3/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 125, in main
    from ..exceptions import conda_exception_handler
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 18, in <module>
    from .common.io import timeout
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 5, in <module>
    from concurrent.futures import ThreadPoolExecutor, _base, as_completed
  File "/srv/gsfs0/software/dx-toolkit/0.234.1/share/dnanexus/lib/python2.7/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/srv/gsfs0/software/dx-toolkit/0.234.1/share/dnanexus/lib/python2.7/site-packages/concurrent/futures/_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
```

Any help will be appreciated.

Thank you

**Comment by leepc12** [comment]
1) Try with `-species hg38`.
2) Remove any conflicting modules (like dxpy) from your ~/.bashrc and try again.

**Comment by ahorn720** [comment]
Thanks for the suggestions.

Im still getting this error though:
```
== checking atac parameters ...
00:00:00.439	Error (/home/ahorning/ATACseq/scripts/atac_dnase_pipelines/modules/align_bowtie2.bds, line 44, pos 3): Bowtie2 index (-bwt2_idx) doesn't exists! (file: .1.bt2 or .1.bt2l)
```

**Comment by leepc12** [comment]
Run `install_genome_data.sh`. (See genome data installation instruction on README.)

**Comment by ahorn720** [comment]
It looks like just about everything worked up until this point:
```
...
2018-03-21 11:39:20 (238 MB/s) - ‘hg38_dnase_avg_fseq_signal_metadata.txt’ saved [5869/5869]

Extracting/processing data files...
Traceback (most recent call last):
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 111, in main
    return activator_main()
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/activate.py", line 578, in main
    print(activator.execute(), end='')
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/activate.py", line 157, in execute
    return getattr(self, self.command)()
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/activate.py", line 143, in activate
    return self._finalize(self._yield_commands(self.build_activate(self.env_name_or_prefix)),
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/activate.py", line 222, in build_activate
    prefix = locate_prefix_by_name(env_name_or_prefix)
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/base/context.py", line 948, in locate_prefix_by_name
    from ..exceptions import EnvironmentNameNotFound
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 18, in <module>
    from .common.io import timeout
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 5, in <module>
    from concurrent.futures import ThreadPoolExecutor, _base, as_completed
  File "/srv/gsfs0/software/dx-toolkit/0.234.1/share/dnanexus/lib/python2.7/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/srv/gsfs0/software/dx-toolkit/0.234.1/share/dnanexus/lib/python2.7/site-packages/concurrent/futures/_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ahorning/miniconda3/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 121, in main
    init_loggers()
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 55, in init_loggers
    from ..gateways.logging import initialize_logging, set_verbosity
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/gateways/logging.py", line 12, in <module>
    from ..common.io import attach_stderr_handler
  File "/home/ahorning/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 5, in <module>
    from concurrent.futures import ThreadPoolExecutor, _base, as_completed
  File "/srv/gsfs0/software/dx-toolkit/0.234.1/share/dnanexus/lib/python2.7/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/srv/gsfs0/software/dx-toolkit/0.234.1/share/dnanexus/lib/python2.7/site-packages/concurrent/futures/_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
```

**Comment by leepc12** [comment]
Remove any conflicting things (like `dxpy`) from your $PATH and ~/.bashrc and try again.

**Comment by leepc12** [comment]
Make sure that you have installed genome database on `/home/ahorning/ATACseq/scripts/atac_dnase_pipelines/genome_data/`. Remove `-chrsz`, `-gensz` and `-seq_dir` from your command line. Also, `-auto_detect_adapter` is a flag so remove TRUE.
```
bds atac.bd~/.bds/bds ~/ATACseq/scripts/atac_dnase_pipelines/atac.bds \
        -species hg38 \
        -enable_idr \
        -auto_detect_adapter \
        -out_dir "${sample}_Peaks_pipeline_out" \
        -title "${sample}" \
        -fastq1_1 "${files[0]}" \
        -fastq1_2 "${files[1]}"
```

**Comment by ahorn720** [comment]
This was very very helpful! Thank you so much!
